# Generated by Django 3.0.5 on 2020-05-25 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='typeofparameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='Type of Parameter', to='ui.Typesofparameter', to_field='name', verbose_name='Type of Parameter'),
        ),
    ]
