# Generated by Django 3.0.5 on 2020-05-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20200525_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limit_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='It is the Limit type for classification of rules as per ITC staff. ex: General, Organic Limit, Residue Limits etc', max_length=255, unique=True, verbose_name='Limit type')),
                ('definition', models.TextField(blank=True, help_text='Put what exactly do you mean by this Limit type', null=True, verbose_name='Definition of the Limit type')),
            ],
            options={
                'verbose_name': 'Limit type',
                'verbose_name_plural': 'Limit Types',
            },
        ),
    ]
