# Generated by Django 3.0.5 on 2020-05-25 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_limit_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintable',
            name='limit_type',
            field=models.ForeignKey(blank=True, default='General', on_delete=django.db.models.deletion.PROTECT, to='ui.Limit_types', to_field='name', verbose_name='Limit type'),
        ),
    ]
